/*Bryan Techera #271868  Martín Lores #285463
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Contrato;
import Dominio.Deposito;
import Dominio.Visita;
import java.util.ArrayList;

public class InformacionDeposito extends javax.swing.JFrame {

    public InformacionDeposito(Deposito deposito, Contrato contrato, ArrayList<Visita> visitas) {
        this.setTitle("Información del deposito: " + deposito.getId());
        initComponents();
        txtDepositoNum.setText(deposito.getId() + "");
        txtTamaño.setText(deposito.getTamaño() + "");
        String estantes = deposito.esEstante() ? "Si" : "No";
        txtEstantes.setText(estantes);
        String refrigerado = deposito.esRefrigerado() ? "Si" : "No";
        txtRefrigerado.setText(refrigerado);

        if (deposito.isAlquilado()) {                           //carga de datos cuando el deposito es alquilado
            String alquilado = deposito.isAlquilado() ? "Si" : "No";
            txtAlquilado.setText(alquilado);
            txtNumContrato.setText(contrato.getId() + "");
            txtNombreCliente.setText(contrato.getCliente().getNombre() + "");
            Visita vis;
            int contador = 0;
            for (int i = 0; i < visitas.size(); i++) {
                vis = visitas.get(i);
                if (vis.getContrato().getId() == contrato.getId()) {
                    contador++;
                }
            }
            txtCantVisitas.setText(contador + "");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDepositoNum = new javax.swing.JLabel();
        txtDepositoNum = new javax.swing.JTextField();
        lblAlquilado = new javax.swing.JLabel();
        txtAlquilado = new javax.swing.JTextField();
        lblTamaño = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        lblNumContrato = new javax.swing.JLabel();
        txtNumContrato = new javax.swing.JTextField();
        lblEstantes = new javax.swing.JLabel();
        txtEstantes = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblRefrigerado = new javax.swing.JLabel();
        txtRefrigerado = new javax.swing.JTextField();
        lblCantVisitas = new javax.swing.JLabel();
        txtCantVisitas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 10, 10));

        lblDepositoNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDepositoNum.setText("Deposito N°:");
        jPanel1.add(lblDepositoNum);

        txtDepositoNum.setEditable(false);
        txtDepositoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositoNumActionPerformed(evt);
            }
        });
        jPanel1.add(txtDepositoNum);

        lblAlquilado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAlquilado.setText("Alquilado:");
        jPanel1.add(lblAlquilado);

        txtAlquilado.setEditable(false);
        txtAlquilado.setText("No");
        txtAlquilado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlquiladoActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlquilado);

        lblTamaño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTamaño.setText("Tamaño:");
        jPanel1.add(lblTamaño);

        txtTamaño.setEditable(false);
        txtTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamañoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTamaño);

        lblNumContrato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumContrato.setText("Contato N°:");
        jPanel1.add(lblNumContrato);

        txtNumContrato.setEditable(false);
        txtNumContrato.setText("-");
        txtNumContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumContratoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumContrato);

        lblEstantes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstantes.setText("Estantes:");
        jPanel1.add(lblEstantes);

        txtEstantes.setEditable(false);
        txtEstantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstantesActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstantes);

        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreCliente.setText("A nombre de:");
        jPanel1.add(lblNombreCliente);

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setText("-");
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreCliente);

        lblRefrigerado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRefrigerado.setText("Refrigerado:");
        jPanel1.add(lblRefrigerado);

        txtRefrigerado.setEditable(false);
        txtRefrigerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefrigeradoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRefrigerado);

        lblCantVisitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCantVisitas.setText("Cantidad de visitas:");
        jPanel1.add(lblCantVisitas);

        txtCantVisitas.setEditable(false);
        txtCantVisitas.setText("-");
        txtCantVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantVisitasActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantVisitas);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 70, 670, 200);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 330, 170, 30);

        setSize(new java.awt.Dimension(791, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumContratoActionPerformed

    private void txtEstantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstantesActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtDepositoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositoNumActionPerformed

    private void txtAlquiladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlquiladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlquiladoActionPerformed

    private void txtTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamañoActionPerformed

    private void txtCantVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantVisitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantVisitasActionPerformed

    private void txtRefrigeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefrigeradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefrigeradoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlquilado;
    private javax.swing.JLabel lblCantVisitas;
    private javax.swing.JLabel lblDepositoNum;
    private javax.swing.JLabel lblEstantes;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumContrato;
    private javax.swing.JLabel lblRefrigerado;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JTextField txtAlquilado;
    private javax.swing.JTextField txtCantVisitas;
    private javax.swing.JTextField txtDepositoNum;
    private javax.swing.JTextField txtEstantes;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumContrato;
    private javax.swing.JTextField txtRefrigerado;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
