/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package Interfaz;

import Controlador.Sistema;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import static javax.swing.UIManager.get;

/**
 *
 * @author Ana Laura
 */
public class MenuVentana extends javax.swing.JFrame {

    
    
    /**
     * Creates new form MenuVentana
     */
    private Sistema sistema;
    private RegistroContrato ventanaContrato;
    private RegistroDeposito ventanaRegistroDeposito;
    private RegistroEmpleado ventanaRegistroEmpleado;
    private RegistroCliente ventanaRegistroCliente;
    private VisitaDepositos ventanaVistaDeposito;
    private Consulta_bajaContrato ventanaBajaContratos;
    private GraficoDepositos ventanaGrafico;
    FondoMenu fondo = new FondoMenu();

    public MenuVentana() {
        this.setVisible(true);
        this.sistema = new Sistema();
        this.ventanaContrato = new RegistroContrato(sistema);
        this.ventanaRegistroDeposito = new RegistroDeposito(sistema);
        this.ventanaRegistroEmpleado = new RegistroEmpleado(sistema);
        this.ventanaRegistroCliente = new RegistroCliente(sistema);
        this.ventanaVistaDeposito = new VisitaDepositos(sistema);
        this.ventanaBajaContratos= new Consulta_bajaContrato(sistema);
        this.ventanaGrafico= new GraficoDepositos(sistema);
        this.setContentPane(fondo);
        sistema.addObserver(ventanaContrato);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        registrosMenu = new javax.swing.JMenu();
        itmRegistroDeposito = new javax.swing.JMenuItem();
        itmRegistroEmpleado = new javax.swing.JMenuItem();
        itmRegistroCliente = new javax.swing.JMenuItem();
        itmRegistroContrato = new javax.swing.JMenuItem();
        visitasMenu = new javax.swing.JMenu();
        itmVisitasDepositos = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        itmConsultaBaja = new javax.swing.JMenuItem();
        itmConsultaDeposito = new javax.swing.JMenuItem();
        estadisticasMenu = new javax.swing.JMenu();
        itmReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        registrosMenu.setMnemonic('f');
        registrosMenu.setText("Registros");

        itmRegistroDeposito.setMnemonic('o');
        itmRegistroDeposito.setText("Registro de deposito");
        itmRegistroDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistroDepositoActionPerformed(evt);
            }
        });
        registrosMenu.add(itmRegistroDeposito);

        itmRegistroEmpleado.setMnemonic('s');
        itmRegistroEmpleado.setText("Registro de empleado ");
        itmRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistroEmpleadoActionPerformed(evt);
            }
        });
        registrosMenu.add(itmRegistroEmpleado);

        itmRegistroCliente.setMnemonic('a');
        itmRegistroCliente.setText("Registro de cliente");
        itmRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistroClienteActionPerformed(evt);
            }
        });
        registrosMenu.add(itmRegistroCliente);

        itmRegistroContrato.setMnemonic('x');
        itmRegistroContrato.setText("Registro de contrato");
        itmRegistroContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistroContratoActionPerformed(evt);
            }
        });
        registrosMenu.add(itmRegistroContrato);

        menuBar.add(registrosMenu);

        visitasMenu.setMnemonic('e');
        visitasMenu.setText("Visitas");

        itmVisitasDepositos.setMnemonic('t');
        itmVisitasDepositos.setText("Visitas de depositos");
        itmVisitasDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVisitasDepositosActionPerformed(evt);
            }
        });
        visitasMenu.add(itmVisitasDepositos);

        menuBar.add(visitasMenu);

        consultasMenu.setMnemonic('h');
        consultasMenu.setText("Consultas");

        itmConsultaBaja.setMnemonic('c');
        itmConsultaBaja.setText("Consulta/baja de contrato");
        itmConsultaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultaBajaActionPerformed(evt);
            }
        });
        consultasMenu.add(itmConsultaBaja);

        itmConsultaDeposito.setMnemonic('a');
        itmConsultaDeposito.setText("Consulta de deposito");
        consultasMenu.add(itmConsultaDeposito);

        menuBar.add(consultasMenu);

        estadisticasMenu.setMnemonic('e');
        estadisticasMenu.setText("Estadisticas");

        itmReporte.setMnemonic('t');
        itmReporte.setText("Generar reporte de ocupación");
        itmReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReporteActionPerformed(evt);
            }
        });
        estadisticasMenu.add(itmReporte);

        menuBar.add(estadisticasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmRegistroContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistroContratoActionPerformed

        this.ventanaContrato.setVisible(true);
    }//GEN-LAST:event_itmRegistroContratoActionPerformed

    private void itmRegistroDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistroDepositoActionPerformed

        this.ventanaRegistroDeposito.setVisible(true);
    }//GEN-LAST:event_itmRegistroDepositoActionPerformed

    private void itmRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistroEmpleadoActionPerformed

        this.ventanaRegistroEmpleado.setVisible(true);
    }//GEN-LAST:event_itmRegistroEmpleadoActionPerformed

    private void itmRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistroClienteActionPerformed

        this.ventanaRegistroCliente.setVisible(true);
    }//GEN-LAST:event_itmRegistroClienteActionPerformed

    private void itmVisitasDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVisitasDepositosActionPerformed

        this.ventanaVistaDeposito.setVisible(true);
    }//GEN-LAST:event_itmVisitasDepositosActionPerformed

    private void itmConsultaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultaBajaActionPerformed

        this.ventanaBajaContratos.setVisible(true);
    }//GEN-LAST:event_itmConsultaBajaActionPerformed

    private void itmReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReporteActionPerformed
        this.ventanaGrafico.setVisible(true);
    }//GEN-LAST:event_itmReporteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenu estadisticasMenu;
    private javax.swing.JMenuItem itmConsultaBaja;
    private javax.swing.JMenuItem itmConsultaDeposito;
    private javax.swing.JMenuItem itmRegistroCliente;
    private javax.swing.JMenuItem itmRegistroContrato;
    private javax.swing.JMenuItem itmRegistroDeposito;
    private javax.swing.JMenuItem itmRegistroEmpleado;
    private javax.swing.JMenuItem itmReporte;
    private javax.swing.JMenuItem itmVisitasDepositos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu registrosMenu;
    private javax.swing.JMenu visitasMenu;
    // End of variables declaration//GEN-END:variables

    class FondoMenu extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
         
            imagen = new ImageIcon(getClass().getResource("/imagenes/SelfStorage.png")).getImage();
            g.drawImage(imagen, 0, 160,getWidth(),50 ,this);
            setOpaque(false);
            super.paint(g);
            //getWidth()
        }
    }

}
