/*Bryan Techera #271868  Martín Lores #285463
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Sistema;
import javax.swing.JOptionPane;

public class RegistroDeposito extends javax.swing.JFrame {

    private Sistema sistema;

    public RegistroDeposito(Sistema sistema) {
        this.sistema = sistema;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estantes = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        grupoEstantes = new javax.swing.ButtonGroup();
        grupoRefrigerado = new javax.swing.ButtonGroup();
        pnlConfiguraciones = new javax.swing.JPanel();
        pnlLables = new javax.swing.JPanel();
        lblTamaño = new javax.swing.JLabel();
        lblEstantes = new javax.swing.JLabel();
        lblRefrigerado = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        txtTamaño = new javax.swing.JTextField();
        lblM2 = new javax.swing.JLabel();
        radio_estantes = new javax.swing.JRadioButton();
        radio_noEstantes = new javax.swing.JRadioButton();
        radio_refrigerado = new javax.swing.JRadioButton();
        radio_noRefrigerado = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de deposito");
        setResizable(false);
        getContentPane().setLayout(null);

        pnlLables.setLayout(new java.awt.GridLayout(3, 1, 0, 25));

        lblTamaño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTamaño.setText("Tamaño:");
        pnlLables.add(lblTamaño);

        lblEstantes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstantes.setText("Estantes:");
        pnlLables.add(lblEstantes);

        lblRefrigerado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRefrigerado.setText("Refrigerado:");
        pnlLables.add(lblRefrigerado);

        pnlOpciones.setLayout(new java.awt.GridLayout(3, 2, 15, 25));

        txtTamaño.setText("0");
        txtTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamañoActionPerformed(evt);
            }
        });
        pnlOpciones.add(txtTamaño);

        lblM2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblM2.setText("m²");
        pnlOpciones.add(lblM2);

        grupoEstantes.add(radio_estantes);
        radio_estantes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        radio_estantes.setText("Con");
        pnlOpciones.add(radio_estantes);

        grupoEstantes.add(radio_noEstantes);
        radio_noEstantes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        radio_noEstantes.setSelected(true);
        radio_noEstantes.setText("Sin");
        pnlOpciones.add(radio_noEstantes);

        grupoRefrigerado.add(radio_refrigerado);
        radio_refrigerado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        radio_refrigerado.setText("Si");
        pnlOpciones.add(radio_refrigerado);

        grupoRefrigerado.add(radio_noRefrigerado);
        radio_noRefrigerado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        radio_noRefrigerado.setSelected(true);
        radio_noRefrigerado.setText("No");
        pnlOpciones.add(radio_noRefrigerado);

        javax.swing.GroupLayout pnlConfiguracionesLayout = new javax.swing.GroupLayout(pnlConfiguraciones);
        pnlConfiguraciones.setLayout(pnlConfiguracionesLayout);
        pnlConfiguracionesLayout.setHorizontalGroup(
            pnlConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfiguracionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlLables, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pnlConfiguracionesLayout.setVerticalGroup(
            pnlConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfiguracionesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(pnlConfiguraciones);
        pnlConfiguraciones.setBounds(30, 40, 570, 220);

        jPanel2.setLayout(null);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(150, 50));
        btnCancelar.setMinimumSize(new java.awt.Dimension(150, 50));
        btnCancelar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(60, 20, 160, 30);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar);
        btnRegistrar.setBounds(230, 20, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 260, 460, 60);

        setSize(new java.awt.Dimension(552, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
        try {
            int dimension = Integer.parseInt(txtTamaño.getText());
            boolean estantes = radio_estantes.isSelected();
            boolean refrigerado = radio_refrigerado.isSelected();
            this.sistema.registrarDeposito(dimension, estantes, refrigerado);
            JOptionPane.showMessageDialog(this, "deposito registrado", "Registro de deposito", JOptionPane.INFORMATION_MESSAGE);
            txtTamaño.setText("0");
            radio_noEstantes.setSelected(true);
            radio_noRefrigerado.setSelected(true);
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamañoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup estantes;
    private javax.swing.ButtonGroup grupoEstantes;
    private javax.swing.ButtonGroup grupoRefrigerado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstantes;
    private javax.swing.JLabel lblM2;
    private javax.swing.JLabel lblRefrigerado;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JPanel pnlConfiguraciones;
    private javax.swing.JPanel pnlLables;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JRadioButton radio_estantes;
    private javax.swing.JRadioButton radio_noEstantes;
    private javax.swing.JRadioButton radio_noRefrigerado;
    private javax.swing.JRadioButton radio_refrigerado;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
