/*Bryan Techera #271868  Martín Lores #285463
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Sistema;
import Dominio.Cliente;
import Dominio.Deposito;
import Dominio.Empleado;
import java.awt.Color;
import java.awt.Component;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class RegistroContrato extends javax.swing.JFrame implements Observer {

    private HashMap<String, Empleado> empleados;
    private HashMap<String, Cliente> clientes;
    private HashMap<Integer, Deposito> depositos;
    private Sistema sistema;

    public RegistroContrato(Sistema sistema) {
        this.sistema = sistema;
        this.empleados = sistema.getEmpleados();
        this.clientes = sistema.getClientes();
        this.depositos = sistema.getDepositos();
        initComponents();
        update(null, "empleado");
        update(null, "cliente");
        

    }

    @Override
    public void update(Observable o, Object arg) {

        String opcion = (String) arg;
        if (opcion.equals("empleado")) {
            DefaultListModel modelEmp = sistema.getModeloEmpleado();
            this.listEmpleados.setModel(modelEmp);
        } else if (opcion.equals("cliente")) {
            DefaultListModel modelCliente = sistema.getModeloCliente();
            this.listClientes.setModel(modelCliente);
        } else if (opcion.equals("deposito")) {
            cargarResultadosBusqueda();
        }
    }

    private void cargarDepositos(int tamMinimo, int tamMaximo, boolean noRelevanteEstan, boolean noRelevanteRefri, boolean conEstan, boolean conRefri) {

        Collection<Deposito> coleccionDeDepositos = this.depositos.values();
        Iterator it = coleccionDeDepositos.iterator();
        //LISTA DEPOSITOS
        DefaultListModel modeloDeListaDepo = new DefaultListModel();
        this.listDepositos.setCellRenderer(new RenderCeldasDepositos());
        this.listDepositos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        while (it.hasNext()) {
            boolean loAgrego = true;
            Deposito miDep = (Deposito) it.next();
            if (miDep.getTamaño() >= tamMinimo && miDep.getTamaño() <= tamMaximo && miDep.isAlquilado() == false) {
                if (!noRelevanteEstan) {
                    //ME PIDEN CON ESTANTES
                    if (miDep.esEstante() != conEstan) {
                        loAgrego = false;
                    }
                }
                if (!noRelevanteRefri) {
                    // ME PIDEN CON REFRIGERACION
                    if (miDep.esRefrigerado() != conRefri) {
                        loAgrego = false;
                    }
                }
            } else {
                loAgrego = false;
            }

            if (loAgrego) {
                modeloDeListaDepo.addElement(miDep);
            }

        }
        this.listDepositos.setModel(modeloDeListaDepo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEstantes = new javax.swing.ButtonGroup();
        grupoRefrigeracion = new javax.swing.ButtonGroup();
        Clientes = new javax.swing.JScrollPane();
        listClientes = new javax.swing.JList();
        txtADetalles = new javax.swing.JPanel();
        lblCaractDep = new javax.swing.JLabel();
        lblTamaño = new javax.swing.JLabel();
        lblEstantes = new javax.swing.JLabel();
        lblRefrigeracion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        pnlEstantes = new javax.swing.JPanel();
        rbESi = new javax.swing.JRadioButton();
        rbENo = new javax.swing.JRadioButton();
        rbENR = new javax.swing.JRadioButton();
        rbRNR = new javax.swing.JRadioButton();
        rbRNo = new javax.swing.JRadioButton();
        rbRSi = new javax.swing.JRadioButton();
        lblMensaje1 = new javax.swing.JLabel();
        panelAcciones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        paneldepositos = new javax.swing.JScrollPane();
        listDepositos = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        Empleados = new javax.swing.JScrollPane();
        listEmpleados = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        lblDepositosDisp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelClientes = new javax.swing.JLabel();
        labelEmpleados = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de contrato");
        getContentPane().setLayout(null);

        listClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Clientes.setViewportView(listClientes);

        getContentPane().add(Clientes);
        Clientes.setBounds(460, 110, 310, 120);

        txtADetalles.setLayout(null);

        lblCaractDep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCaractDep.setText("Caracteristicas del deposito");
        txtADetalles.add(lblCaractDep);
        lblCaractDep.setBounds(107, 0, 250, 25);

        lblTamaño.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTamaño.setText("Tamaño");
        txtADetalles.add(lblTamaño);
        lblTamaño.setBounds(30, 40, 57, 22);

        lblEstantes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEstantes.setText("Estantes");
        txtADetalles.add(lblEstantes);
        lblEstantes.setBounds(150, 40, 57, 22);

        lblRefrigeracion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRefrigeracion.setText("Refrigeración");
        txtADetalles.add(lblRefrigeracion);
        lblRefrigeracion.setBounds(290, 40, 113, 22);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, -30, 20));

        jLabel6.setText("Mínimo");
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel6KeyTyped(evt);
            }
        });
        jPanel1.add(jLabel6);

        txtMin.setText("0");
        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });
        txtMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMinKeyPressed(evt);
            }
        });
        jPanel1.add(txtMin);

        jLabel7.setText("Máximo");
        jPanel1.add(jLabel7);

        txtMax.setText("0");
        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });
        jPanel1.add(txtMax);

        txtADetalles.add(jPanel1);
        jPanel1.setBounds(10, 80, 120, 80);

        pnlEstantes.setLayout(new java.awt.GridLayout(3, 0));

        grupoEstantes.add(rbESi);
        rbESi.setText("Si");
        rbESi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbESiActionPerformed(evt);
            }
        });
        pnlEstantes.add(rbESi);

        grupoEstantes.add(rbENo);
        rbENo.setText("No");
        rbENo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbENoActionPerformed(evt);
            }
        });
        pnlEstantes.add(rbENo);

        grupoEstantes.add(rbENR);
        rbENR.setSelected(true);
        rbENR.setText("No relevante");
        rbENR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbENRActionPerformed(evt);
            }
        });
        pnlEstantes.add(rbENR);

        txtADetalles.add(pnlEstantes);
        pnlEstantes.setBounds(150, 70, 100, 100);

        grupoRefrigeracion.add(rbRNR);
        rbRNR.setSelected(true);
        rbRNR.setText("No relevante");
        rbRNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRNRActionPerformed(evt);
            }
        });
        txtADetalles.add(rbRNR);
        rbRNR.setBounds(290, 140, 140, 20);

        grupoRefrigeracion.add(rbRNo);
        rbRNo.setText("No");
        rbRNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRNoActionPerformed(evt);
            }
        });
        txtADetalles.add(rbRNo);
        rbRNo.setBounds(290, 110, 60, 20);

        grupoRefrigeracion.add(rbRSi);
        rbRSi.setText("Si");
        rbRSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRSiActionPerformed(evt);
            }
        });
        txtADetalles.add(rbRSi);
        rbRSi.setBounds(290, 80, 40, 20);

        getContentPane().add(txtADetalles);
        txtADetalles.setBounds(30, 510, 460, 190);

        lblMensaje1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMensaje1.setText("Seleccione un empleado, el cliente y las caracteristicas deseadas de los depositos que busca.");
        getContentPane().add(lblMensaje1);
        lblMensaje1.setBounds(60, 10, 790, 30);

        panelAcciones.setLayout(null);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnCancelar);
        btnCancelar.setBounds(0, 30, 140, 40);

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnReservar);
        btnReservar.setBounds(150, 30, 140, 40);

        getContentPane().add(panelAcciones);
        panelAcciones.setBounds(530, 580, 290, 90);

        paneldepositos.setViewportView(listDepositos);

        getContentPane().add(paneldepositos);
        paneldepositos.setBounds(30, 330, 360, 110);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 480, 810, 10);

        listEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listEmpleados.setToolTipText("");
        Empleados.setViewportView(listEmpleados);

        getContentPane().add(Empleados);
        Empleados.setBounds(30, 110, 350, 120);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(460, 330, 310, 110);

        btnBuscar.setText("Buscar depositos");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(520, 510, 140, 30);

        lblDepositosDisp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDepositosDisp.setText("Depositos disponibles");
        getContentPane().add(lblDepositosDisp);
        lblDepositosDisp.setBounds(110, 270, 190, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Detalles");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 270, 70, 40);

        labelClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelClientes.setText("Clientes");
        getContentPane().add(labelClientes);
        labelClientes.setBounds(570, 60, 90, 40);

        labelEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEmpleados.setText("Empleados");
        getContentPane().add(labelEmpleados);
        labelEmpleados.setBounds(160, 60, 110, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 250, 810, 10);

        setSize(new java.awt.Dimension(866, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();


    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        cargarResultadosBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        cargarResultadosBusqueda();
    }//GEN-LAST:event_txtMinActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed

        Empleado empleado = (Empleado) this.listEmpleados.getSelectedValue();
        Cliente cliente = (Cliente) this.listClientes.getSelectedValue();
        List<Deposito> listDepos = this.listDepositos.getSelectedValuesList();
        String desc = txtArea.getText();
        try {
            this.sistema.registrarContrato(empleado, cliente, listDepos, desc);

            JOptionPane.showMessageDialog(this, "Contrato creado", "Registro de contrato", JOptionPane.INFORMATION_MESSAGE);
            this.listDepositos.setModel(new DefaultListModel());

            txtMin.setText("1");
            txtMax.setText("9999");

            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnReservarActionPerformed

    private void rbENoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbENoActionPerformed
        cargarResultadosBusqueda();
    }//GEN-LAST:event_rbENoActionPerformed

    private void rbESiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbESiActionPerformed
        cargarResultadosBusqueda();

    }//GEN-LAST:event_rbESiActionPerformed

    private void rbENRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbENRActionPerformed

        cargarResultadosBusqueda();
    }//GEN-LAST:event_rbENRActionPerformed

    private void rbRSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRSiActionPerformed
        cargarResultadosBusqueda();
    }//GEN-LAST:event_rbRSiActionPerformed

    private void rbRNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRNoActionPerformed
        cargarResultadosBusqueda();
    }//GEN-LAST:event_rbRNoActionPerformed

    private void rbRNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRNRActionPerformed
        cargarResultadosBusqueda();
    }//GEN-LAST:event_rbRNRActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        cargarResultadosBusqueda();
    }//GEN-LAST:event_txtMaxActionPerformed

    private void txtMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinKeyPressed

    }//GEN-LAST:event_txtMinKeyPressed

    private void jLabel6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyTyped

    }//GEN-LAST:event_jLabel6KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Clientes;
    private javax.swing.JScrollPane Empleados;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.ButtonGroup grupoEstantes;
    private javax.swing.ButtonGroup grupoRefrigeracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelClientes;
    private javax.swing.JLabel labelEmpleados;
    private javax.swing.JLabel lblCaractDep;
    private javax.swing.JLabel lblDepositosDisp;
    private javax.swing.JLabel lblEstantes;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblRefrigeracion;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JList listClientes;
    private javax.swing.JList listDepositos;
    private javax.swing.JList listEmpleados;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JScrollPane paneldepositos;
    private javax.swing.JPanel pnlEstantes;
    private javax.swing.JRadioButton rbENR;
    private javax.swing.JRadioButton rbENo;
    private javax.swing.JRadioButton rbESi;
    private javax.swing.JRadioButton rbRNR;
    private javax.swing.JRadioButton rbRNo;
    private javax.swing.JRadioButton rbRSi;
    private javax.swing.JPanel txtADetalles;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    // End of variables declaration//GEN-END:variables

    private void cargarResultadosBusqueda() {
        try {
            if (this.txtMin.getText().startsWith("0") || this.txtMax.getText().startsWith("0")) {
                throw new NumberFormatException();
            }
            int tamMinimo = Integer.parseInt(this.txtMin.getText());
            int tamMax = Integer.parseInt(this.txtMax.getText());

            boolean noRelevanteEstan = this.rbENR.isSelected();
            boolean noRelevanteRefri = this.rbRNR.isSelected();

            boolean conEstan = this.rbESi.isSelected();
            boolean conRefri = this.rbRSi.isSelected();

            cargarDepositos(tamMinimo, tamMax, noRelevanteEstan, noRelevanteRefri, conEstan, conRefri);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Introduzca un tamaño valido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}

class RenderCeldasDepositos extends DefaultListCellRenderer {

    @Override           //metodo para darle color a los depositos según sus caracteristicas
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        Component miCelda = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

        Deposito dep = (Deposito) value;

        if (dep.esEstante() && dep.esRefrigerado()) {
            miCelda.setBackground(Color.GREEN);
        } else if (dep.esEstante() && !dep.esRefrigerado()) {
            miCelda.setBackground(Color.ORANGE);
        } else if (!dep.esEstante() && dep.esRefrigerado()) {
            miCelda.setBackground(Color.YELLOW);
        } else if (!dep.esEstante() && !dep.esRefrigerado()) {
            miCelda.setBackground(Color.CYAN);
        }
        if (isSelected) {
            miCelda.setBackground(Color.LIGHT_GRAY);
        }
        return miCelda;
    }

}
