/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Controlador.Sistema;

/**
 *
 * @author Martin
 */
public class VisitaDepositos extends javax.swing.JFrame {

    /**
     * Creates new form VisitaDepositos
     */
    public VisitaDepositos(Sistema sistema) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        listEmpleados = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        lblMes = new javax.swing.JLabel();
        lblEmpleados = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        comboDia = new javax.swing.JComboBox();
        comboMes = new javax.swing.JComboBox<>();
        listContratos = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        lblContratos = new javax.swing.JLabel();
        listClientes = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        lblClientes = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDatos.setLayout(null);

        jList3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listEmpleados.setViewportView(jList3);

        pnlDatos.add(listEmpleados);
        listEmpleados.setBounds(300, 80, 110, 190);

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMes.setText("Mes");
        pnlDatos.add(lblMes);
        lblMes.setBounds(560, 130, 29, 22);

        lblEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleados.setText("Empleados");
        pnlDatos.add(lblEmpleados);
        lblEmpleados.setBounds(320, 50, 90, 22);

        lblDia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDia.setText("Día");
        pnlDatos.add(lblDia);
        lblDia.setBounds(470, 130, 50, 22);

        comboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaActionPerformed(evt);
            }
        });
        pnlDatos.add(comboDia);
        comboDia.setBounds(450, 170, 72, 22);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        pnlDatos.add(comboMes);
        comboMes.setBounds(540, 170, 72, 22);

        jList4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listContratos.setViewportView(jList4);

        pnlDatos.add(listContratos);
        listContratos.setBounds(170, 80, 110, 190);

        lblContratos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblContratos.setText("Contratos");
        pnlDatos.add(lblContratos);
        lblContratos.setBounds(190, 50, 80, 22);

        jList5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listClientes.setViewportView(jList5);

        pnlDatos.add(listClientes);
        listClientes.setBounds(40, 80, 110, 190);

        lblClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblClientes.setText("Clientes");
        pnlDatos.add(lblClientes);
        lblClientes.setBounds(70, 50, 60, 22);

        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(150, 50));
        btnCancelar.setMinimumSize(new java.awt.Dimension(150, 50));
        btnCancelar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnRegistrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(676, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

       
       
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblContratos;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblMes;
    private javax.swing.JScrollPane listClientes;
    private javax.swing.JScrollPane listContratos;
    private javax.swing.JScrollPane listEmpleados;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    // End of variables declaration//GEN-END:variables
}
